[package]
name = "softcore_sc_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.28.0"
egui_plot = "0.28.0"
eframe = "0.28.0"
splines = "4.3.1"
plotters = "0.3.6"
csv = "1.3.0"
serde = { version = "1.0", features = ["derive"] }